const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  runtime: [
    {type: 'autogenerated', dirName: '.'}
  ],
  stdlib: [
    {type: 'autogenerated', dirName: '.'}
  ],
  deploy: [
    {type: 'autogenerated', dirName: '.'}
  ],
};

module.exports = sidebars;
