// Include main doc categories on most pages
const mainMenu = [
  {
    type: "html",
    value: "<div>Deno Deploy</div>",
    className: "product-header",
  },
  // https://docusaurus.io/docs/sidebar/items
  {
    type: "link",
    href: "/deploy/manual",
    label: "Manual",
    className: "icon-menu-option icon-menu-user-guide",
  },
  {
    type: "link",
    label: "Tutorials & Examples",
    href: "/deploy/tutorials",
    className: "icon-menu-option icon-menu-tutorials",
  },
  {
    type: "link",
    label: "API Reference",
    href: "/deploy/api",
    className: "icon-menu-option icon-menu-api",
  },
];

const sidebars = {
  deploy: mainMenu,

  deployGuideHome: mainMenu.concat([
    {
      type: "html",
      value: "<div>Manual</div>",
      className: "section-header",
    },
    {
      type: "doc",
      label: "Quick Start",
      id: "manual/index",
    },
    {
      type: "category",
      label: "Deploy Basics",
      items: [
        "manual/use-cases",
        "manual/playgrounds",
        "manual/how-to-deploy",
        "manual/ci_github",
        "manual/deployctl",
        "manual/regions",
        "manual/pricing-and-limits",
      ],
    },
    {
      type: "category",
      label: "Projects & Organizations",
      items: [
        "manual/deployments",
        "manual/custom-domains",
        "manual/environment-variables",
        "manual/organizations",
        "manual/logs",
      ],
    },
    {
      type: "category",
      label: "Connect to Databases",
      items: [
        {
          type: "link",
          href: "/kv/manual/on_deploy",
          label: "Deno KV",
        },
        "manual/dynamodb",
        "manual/faunadb",
        "manual/firebase",
        "manual/postgres",
      ],
    },
    {
      type: "category",
      label: "Policies & Fair Use",
      items: [
        "manual/fair-use-policy",
        "manual/privacy-policy",
        "manual/security",
      ],
    },
    {
      type: "html",
      value: '<div style="height: 30px;"></div>',
    },
  ]),

  deployTutorialsHome: mainMenu.concat([
    {
      type: "html",
      value: "<div>Tutorials &amp; Examples</div>",
      className: "section-header",
    },
    {
      type: "autogenerated",
      dirName: "tutorials",
    },
    {
      type: "link",
      label: "More on Deno by Example",
      href: "https://examples.deno.land",
    },
    {
      type: "html",
      value: '<div style="height: 30px;"></div>',
    },
  ]),

  deployAPIHome: mainMenu.concat([
    {
      type: "html",
      value: "<div>Runtime APIs</div>",
      className: "section-header",
    },
    "api/index",
    "api/runtime-fs",
    "api/runtime-node",
    "api/compression",
    "api/runtime-sockets",
    "api/runtime-broadcast-channel",
    "api/runtime-fetch",
    "api/runtime-request",
    "api/runtime-response",
    "api/runtime-headers",
    {
      type: "html",
      value: "<div>REST API</div>",
      className: "section-header",
    },
    {
      type: "doc",
      label: "Overview",
      id: "api/rest/index",
    },
    "api/rest/organizations",
    "api/rest/projects",
    "api/rest/deployments",
    "api/rest/domains",
    {
      type: "html",
      value: '<div style="height: 30px;"></div>',
    },
  ]),
};

module.exports = sidebars;
