/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Deno Docs",
  "tagline":
    "Deno is the next generation runtime for JavaScript and TypeScript.",
  "favicon": "img/favicon.ico",
  "url": "https://docs.deno.com",
  "baseUrl": "/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en",
    ],
    "path": "i18n",
    "localeConfigs": {},
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "id": "runtime",
          "path": "runtime",
          "routeBasePath": "runtime",
          "sidebarPath":
            "/Users/andyjiang/Developer/deno/deno-docs/sidebars/runtime.js",
          "remarkPlugins": [
            null,
          ],
        },
        "theme": {
          "customCss":
            "/Users/andyjiang/Developer/deno/deno-docs/src/css/custom.css",
        },
        "googleTagManager": {
          "containerId": "GTM-5B5TH8ZJ",
        },
      },
    ],
  ],
  "plugins": [
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "deploy",
        "path": "deploy",
        "routeBasePath": "/deploy",
        "sidebarPath":
          "/Users/andyjiang/Developer/deno/deno-docs/sidebars/deploy.js",
        "remarkPlugins": [
          null,
        ],
      },
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "kv",
        "path": "kv",
        "routeBasePath": "/kv",
        "sidebarPath":
          "/Users/andyjiang/Developer/deno/deno-docs/sidebars/kv.js",
        "remarkPlugins": [
          null,
        ],
      },
    ],
    null,
    null,
  ],
  "themeConfig": {
    "image": "img/social.png",
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false,
    },
    "navbar": {
      "title": "Deno Docs",
      "logo": {
        "alt": "Deno",
        "src": "img/logo.svg",
        "srcDark": "img/logo-dark.svg",
        "href": "/",
      },
      "items": [
        {
          "to": "/runtime/manual",
          "position": "left",
          "label": "Runtime",
          "activeBaseRegex": "^/runtime",
        },
        {
          "to": "/deploy/manual",
          "position": "left",
          "label": "Deploy",
          "activeBaseRegex": "^/deploy",
        },
        {
          "to": "/kv/manual",
          "position": "left",
          "label": "KV",
          "activeBaseRegex": "^/kv",
        },
        {
          "href": "https://www.deno.land/std",
          "label": "Std. Library",
          "position": "left",
        },
        {
          "href": "https://www.deno.com",
          "label": "deno.com",
          "position": "right",
        },
      ],
      "hideOnScroll": false,
    },
    "sidebar": {
      "hideable": true,
    },
    "docs": {
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": true,
      },
      "versionPersistence": "localStorage",
    },
    "footer": {
      "style": "light",
      "links": [
        {
          "title": "Deno Docs",
          "items": [
            {
              "label": "Deno Runtime",
              "to": "/runtime/manual",
            },
            {
              "label": "Deno Deploy",
              "to": "/deploy/manual",
            },
            {
              "label": "Deno KV",
              "to": "/kv/manual",
            },
            {
              "label": "Standard Library",
              "href": "https://deno.land/std",
            },
            {
              "label": "Deno by Example",
              "href": "https://examples.deno.land",
            },
          ],
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Discord",
              "href": "https://discord.gg/deno",
            },
            {
              "label": "GitHub",
              "href": "https://github.com/denoland",
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/deno_land",
            },
            {
              "label": "YouTube",
              "href": "https://youtube.com/@deno_land",
            },
            {
              "label": "Newsletter",
              "href": "https://deno.news/",
            },
          ],
        },
        {
          "title": "Help & Feedback",
          "items": [
            {
              "label": "Community Support",
              "href": "https://discord.gg/deno",
            },
            {
              "label": "Deploy System Status",
              "href": "https://www.denostatus.com",
            },
            {
              "label": "Deploy Feedback",
              "href": "https://github.com/denoland/deploy_feedback",
            },
            {
              "label": "Report a Problem",
              "href": "mailto:support@deno.com",
            },
          ],
        },
        {
          "title": "Company",
          "items": [
            {
              "label": "Blog",
              "href": "https://www.deno.com/blog",
            },
            {
              "label": "Careers",
              "href": "https://deno.com/jobs",
            },
            {
              "label": "Merch",
              "href": "https://merch.deno.com/",
            },
            {
              "label": "Privacy Policy",
              "href": "/deploy/manual/privacy-policy",
            },
          ],
        },
      ],
      "copyright": "Copyright © 2023 the Deno authors.",
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa",
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata",
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic",
            },
          },
          {
            "types": [
              "namespace",
            ],
            "style": {
              "opacity": 0.7,
            },
          },
          {
            "types": [
              "string",
              "attr-value",
            ],
            "style": {
              "color": "#e3116c",
            },
          },
          {
            "types": [
              "punctuation",
              "operator",
            ],
            "style": {
              "color": "#393A34",
            },
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted",
            ],
            "style": {
              "color": "#36acaa",
            },
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector",
            ],
            "style": {
              "color": "#00a4db",
            },
          },
          {
            "types": [
              "function",
              "deleted",
              "tag",
            ],
            "style": {
              "color": "#d73a49",
            },
          },
          {
            "types": [
              "function-variable",
            ],
            "style": {
              "color": "#6f42c1",
            },
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword",
            ],
            "style": {
              "color": "#00009f",
            },
          },
        ],
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36",
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin",
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
            },
          },
          {
            "types": [
              "inserted",
              "function",
            ],
            "style": {
              "color": "rgb(80, 250, 123)",
            },
          },
          {
            "types": [
              "deleted",
            ],
            "style": {
              "color": "rgb(255, 85, 85)",
            },
          },
          {
            "types": [
              "changed",
            ],
            "style": {
              "color": "rgb(255, 184, 108)",
            },
          },
          {
            "types": [
              "punctuation",
              "symbol",
            ],
            "style": {
              "color": "rgb(248, 248, 242)",
            },
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector",
            ],
            "style": {
              "color": "rgb(255, 121, 198)",
            },
          },
          {
            "types": [
              "keyword",
              "variable",
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic",
            },
          },
          {
            "types": [
              "comment",
            ],
            "style": {
              "color": "rgb(98, 114, 164)",
            },
          },
          {
            "types": [
              "attr-name",
            ],
            "style": {
              "color": "rgb(241, 250, 140)",
            },
          },
        ],
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end",
          },
        },
      ],
    },
    "algolia": {
      "appId": "KAQ4QIALEB",
      "apiKey": "0795dfc12048ff344a54bb4c04c9000b",
      "indexName": "deno",
      "insights": true,
      "contextualSearch": true,
      "searchParameters": {},
      "searchPagePath": "search",
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3,
    },
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static",
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false,
  },
};
